# Generated by Django 6.0.3 on 2026-03-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория туризма')),
                ('hashtag', models.CharField(max_length=100, verbose_name='Хэштег категории')),
            ],
            options={
                'verbose_name': 'Категория туризма',
                'verbose_name_plural': 'Категории туризма',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО туриста')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('location', models.CharField(max_length=100, verbose_name='Место тура')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена тура')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность в днях')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(to='tourism.tourcategory', verbose_name='Категории туризма')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата записи')),
                ('people_count', models.PositiveIntegerField(verbose_name='Количество людей')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.tour', verbose_name='Тур')),
                ('tourist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourism.tourist', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Запись на тур',
                'verbose_name_plural': 'Записи на тур',
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(verbose_name='Оценка')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Отзыв о туре',
                'verbose_name_plural': 'Отзывы о туре',
            },
        ),
    ]
