# Generated by Django 6.0.3 on 2026-03-23 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITVacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='vacancy_photos/', verbose_name='Фото')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('desired_position', models.CharField(default='IT специалист', max_length=120, verbose_name='Желаемая позиция')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж работы (лет)')),
                ('education', models.TextField(verbose_name='Образование')),
                ('key_skills', models.TextField(verbose_name='Ключевые навыки')),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Желаемая зарплата')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('internship', 'Стажировка')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('work_format', models.CharField(choices=[('office', 'Офис'), ('remote', 'Удаленно'), ('hybrid', 'Гибрид')], default='office', max_length=20, verbose_name='Формат работы')),
                ('english_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Уровень английского')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Ссылка на портфолио')),
                ('github_url', models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('about_yourself', models.TextField(verbose_name='О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анкета IT специалиста',
                'verbose_name_plural': 'Анкеты IT специалистов',
                'ordering': ['-id'],
            },
        ),
    ]
