# Generated by Django 6.0.3 on 2026-03-23 08:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSpecialistApplicant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(upload_to='it_applicants/')),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('desired_position', models.CharField(default='IT Specialist', max_length=120)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.TextField()),
                ('key_skills', models.TextField()),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('english_level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], default='BEGINNER', max_length=20)),
                ('work_format', models.CharField(choices=[('OFFICE', 'OFFICE'), ('REMOTE', 'REMOTE'), ('HYBRID', 'HYBRID')], default='OFFICE', max_length=20)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('ready_to_relocate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='ITVacancyApplication',
        ),
    ]
