# Generated by Django 6.0.3 on 2026-03-18 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_facts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='ФИО водителя', max_length=100)),
                ('photo', models.ImageField(upload_to='drivers/')),
                ('birth_date', models.DateField()),
                ('driving_experience', models.PositiveIntegerField(default=1)),
                ('driver_license', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_facts.car')),
            ],
        ),
    ]
