# Generated by Django 6.0.3 on 2026-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('body_type', models.CharField(max_length=100, verbose_name='Тип кузова')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('horsepower', models.PositiveIntegerField(verbose_name='Лошадиные силы')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Изображение')),
                ('is_electric', models.BooleanField(default=False, verbose_name='Электромобиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['title', '-year'],
            },
        ),
    ]
