# Generated by Django 6.0.3 on 2026-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Просмотры'),
        ),
    ]
