# Generated by Django 6.0.3 on 2026-03-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_electric',
        ),
    ]
